routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('personas','PersonaController');
Route::resource('tipo_actividades','TipoActividadController');
Route::resource('actividades','ActividadController');
Route::resource('expedientes','ExpedienteController');
Route::resource('calendarios','CalendarioController');
Route::resource('notas','NotaController');
Route::resource('distritos','DistritoController');
Route::resource('juzgados','JuzgadoController');

resources/views/layouts/menu/breadcrumb.blade.php
<div class="kt-subheader   kt-grid__item" id="kt_subheader">
    <div class="kt-container  kt-container--fluid ">
        <div class="kt-subheader__main">
            <h3 class="kt-subheader__title">Dashboard</h3>
            <span class="kt-subheader__separator kt-hidden"></span>
            <div class="kt-subheader__breadcrumbs">
                <a href="#" class="kt-subheader__breadcrumbs-home"><i class="flaticon2-shelter bg-color-navbar"></i></a>
                <span class="kt-subheader__breadcrumbs-separator"></span>
                <a href="#" class="kt-subheader__breadcrumbs-link bg-color-navbar">
                    Dashboards
                </a>
                <span class="kt-subheader__breadcrumbs-separator"></span>
                <a href="" class="kt-subheader__breadcrumbs-link bg-color-navbar">
                    Navy Aside
                </a>
			</div>
        </div>

    </div>
</div>

resources/views/layouts/menu/header_movil.blade.php
 <!-- begin:: Header Mobile -->
<div id="kt_header_mobile" class="kt-header-mobile  kt-header-mobile--fixed ">
    <div class="kt-header-mobile__logo">
        <a href="#">
            <!--<img alt="Logo" src="assets/media/logos/logo-6.png" />-->
        </a>
    </div>
    <div class="kt-header-mobile__toolbar">
        <button class="kt-header-mobile__toolbar-toggler kt-header-mobile__toolbar-toggler--left" id="kt_aside_mobile_toggler"><span></span></button>
        <button class="kt-header-mobile__toolbar-topbar-toggler" id="kt_header_mobile_topbar_toggler"><i class="flaticon-more"></i></button>
    </div>
</div>

resources/views/layouts/menu/navAside.blade.php
<!-- begin:: Aside -->
<button class="kt-aside-close " id="kt_aside_close_btn"><i class="la la-close"></i></button>
<div class="kt-aside  kt-aside--fixed bg-color-sidebar" id="kt_aside">

    <div class="kt-aside__brand kt-grid__item bg-color-sidebar" id="kt_aside_brand">
        <div class="kt-aside__brand-logo">
            <a href="#">
                <!--<img alt="Logo" src="img/logo-setra.jpg" style="width:88px; height:50px;"/>-->
            </a>
        </div>
        <div class="kt-aside__brand-tools">
            <button class="kt-aside__brand-aside-toggler kt-aside__brand-aside-toggler--left" id="kt_aside_toggler"><span></span></button>
        </div>
    </div>

    <div class="kt-aside-menu-wrapper kt-grid__item kt-grid__item--fluid" id="kt_aside_menu_wrapper">
        <div id="kt_aside_menu" class="kt-aside-menu bg-color-sidebar" data-ktmenu-vertical="1" data-ktmenu-scroll="1" data-ktmenu-dropdown-timeout="500">
            <ul class="kt-menu__nav ">
                <li class="kt-menu__item  kt-menu__item--submenu kt-menu__item--open kt-menu__item--here" aria-haspopup="true" data-ktmenu-submenu-toggle="hover">
                    <a href="{{ route('home')}}" class="kt-menu__link bg-color-sidebar"><i class="kt-menu__link-icon flaticon2-graphic"></i><span class="kt-menu__link-text">Dashboards</span></a>
                </li>
                <li class="kt-menu__section ">
                    <h4 class="kt-menu__section-text colorTituloGrupal">Recepcion</h4>
                    <i class="kt-menu__section-icon flaticon-more-v2"></i>
                </li>

                <li class="kt-menu__item  kt-menu__item--submenu" aria-haspopup="true" data-ktmenu-submenu-toggle="hover">
                    <a href="{{ route('distritos.index')}}" class="kt-menu__link"><i class="kt-menu__link-icon flaticon2-copy">
                        </i><span class="kt-menu__link-text">Distrito</span></a>
                    <div class="kt-menu__submenu ">
                        <span class="kt-menu__arrow"></span>
                    </div>
                </li>

                <li class="kt-menu__item  kt-menu__item--submenu" aria-haspopup="true" data-ktmenu-submenu-toggle="hover">
                    <a href="{{ route('juzgados.index')}}" class="kt-menu__link"><i class="kt-menu__link-icon flaticon2-copy">
                        </i><span class="kt-menu__link-text">Juzgado</span></a>
                    <div class="kt-menu__submenu ">
                        <span class="kt-menu__arrow"></span>
                    </div>
                </li>

                <li class="kt-menu__item  kt-menu__item--submenu" aria-haspopup="true" data-ktmenu-submenu-toggle="hover">
                    <a href="{{ route('tipo_actividades.index')}}" class="kt-menu__link"><i class="kt-menu__link-icon flaticon2-copy">
                        </i><span class="kt-menu__link-text">Tipo Actividad</span></a>
                    <div class="kt-menu__submenu ">
                        <span class="kt-menu__arrow"></span>
                    </div>
                </li>

                <li class="kt-menu__item  kt-menu__item--submenu" aria-haspopup="true" data-ktmenu-submenu-toggle="hover">
                    <a href="{{ route('personas.index')}}" class="kt-menu__link"><i class="kt-menu__link-icon flaticon2-copy"></i><span class="kt-menu__link-text">Persona</span></a>
                    <div class="kt-menu__submenu ">
                        <span class="kt-menu__arrow"></span>
                    </div>
                </li>

                <li class="kt-menu__item  kt-menu__item--submenu" aria-haspopup="true" data-ktmenu-submenu-toggle="hover">
                    <a href="{{ route('actividades.index')}}" class="kt-menu__link"><i class="kt-menu__link-icon flaticon2-copy">
                        </i><span class="kt-menu__link-text">Actividad</span></a>
                    <div class="kt-menu__submenu ">
                        <span class="kt-menu__arrow"></span>
                    </div>
                </li>

                <li class="kt-menu__item  kt-menu__item--submenu" aria-haspopup="true" data-ktmenu-submenu-toggle="hover">
                    <a href="{{ route('expedientes.index')}}" class="kt-menu__link"><i class="kt-menu__link-icon flaticon2-copy"></i><span class="kt-menu__link-text">Expediente</span></a>
                    <div class="kt-menu__submenu ">
                        <span class="kt-menu__arrow"></span>
                    </div>
                </li>

                <li class="kt-menu__item  kt-menu__item--submenu" aria-haspopup="true" data-ktmenu-submenu-toggle="hover">
                    <a href="{{ route('notas.index')}}" class="kt-menu__link"><i class="kt-menu__link-icon flaticon2-copy"></i><span class="kt-menu__link-text">Nota</span></a>
                    <div class="kt-menu__submenu ">
                        <span class="kt-menu__arrow"></span>
                    </div>
                </li>

                <li class="kt-menu__item  kt-menu__item--submenu" aria-haspopup="true" data-ktmenu-submenu-toggle="hover">
                    <a href="{{ route('calendarios.index')}}" class="kt-menu__link"><i class="kt-menu__link-icon flaticon2-copy"></i><span class="kt-menu__link-text">Calendario</span></a>
                    <div class="kt-menu__submenu ">
                        <span class="kt-menu__arrow"></span>
                    </div>
                </li>

            </ul>
        </div>
    </div>

</div>
<!-- end:: Aside -->

resources/views/layouts/menu/topHeader.blade.php
<div id="kt_header" class="kt-header kt-grid__item  kt-header--fixed ">

        <!-- begin:: Header Menu -->
        <button class="kt-header-menu-wrapper-close" id="kt_header_menu_mobile_close_btn"><i class="la la-close"></i></button>
        <div class="kt-header-menu-wrapper" id="kt_header_menu_wrapper">

        </div>

        <!-- end:: Header Menu -->
        <!-- begin:: Header Topbar -->
        <div class="kt-header__topbar">
            <!--begin:: Languages -->
            <div class="kt-header__topbar-item kt-header__topbar-item--langs">
                <div class="kt-header__topbar-wrapper" data-toggle="dropdown" data-offset="10px,0px">
                    <span class="kt-header__topbar-icon kt-rounded-">
                        <img class="" src="{{asset('assets/media/flags/020-flag.svg')}}" alt="" />
                    </span>
                </div>
                <div class="dropdown-menu dropdown-menu-fit dropdown-menu-right dropdown-menu-anim dropdown-menu-top-unround">
                    <ul class="kt-nav kt-margin-t-10 kt-margin-b-10">
                        <li class="kt-nav__item">
                            <a href="#" class="kt-nav__link">
                                <span class="kt-nav__link-icon"><img src="{{asset('assets/media/flags/016-spain.svg')}}" alt="" /></span>
                                <span class="kt-nav__link-text">Spanish</span>
                            </a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else

                        @endguest
                    </ul>
                </div>
            </div>

            <!--end:: Languages -->
            <!--begin: User Bar -->
            <div class="kt-header__topbar-item kt-header__topbar-item--user">
                <div class="kt-header__topbar-wrapper" data-toggle="dropdown" data-offset="0px,0px">

                    <!--use "kt-rounded" class for rounded avatar style-->
                    <div class="kt-header__topbar-user kt-rounded-">
                        <span class="kt-header__topbar-welcome kt-hidden-mobile">Hi,</span>
                        <span class="kt-header__topbar-username kt-hidden-mobile">
                              <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                              {{ Auth::user()->name }}
                        @endguest

                          <span class="caret"></span></span>
                        <img alt="Pic" src="{{asset('assets/media/users/default.jpg')}}" class="kt-rounded-" />

                        <!--use below badge element instead the user avatar to display username's first letter(remove kt-hidden class to display it) -->
                        <span class="kt-badge kt-badge--username kt-badge--lg kt-badge--brand kt-hidden kt-badge--bold">S</span>
                    </div>
                </div>
                <div class="dropdown-menu dropdown-menu-fit dropdown-menu-right dropdown-menu-anim dropdown-menu-top-unround dropdown-menu-sm">
                    <div class="kt-user-card kt-margin-b-40 kt-margin-b-30-tablet-and-mobile">
                        <div class="kt-user-card__wrapper">
                            <div class="kt-user-card__pic">

                                <!--use "kt-rounded" class for rounded avatar style-->
                                <img alt="Pic" src="{{asset('assets/media/users/default.jpg')}}" class="kt-rounded-" />
                            </div>
                            <div class="kt-user-card__details">
                                <div class="kt-user-card__name">Luis</div>
                                <div class="kt-user-card__position">Santa.</div>
                            </div>
                        </div>
                    </div>
                    <ul class="kt-nav kt-margin-b-10">

                        <li class="kt-nav__separator kt-nav__separator--fit"></li>
                        <li class="kt-nav__custom kt-space-between">
                            <a href="#" class="btn btn-profile btn-upper btn-sm" data-toggle="modal" data-target="#logoutModal">Sign Out</a>
                            <i class="flaticon2-information kt-label-font-color-2" data-toggle="kt-tooltip" data-placement="right" title="" data-original-title="Click to learn more..."></i>
                        </li>
                    </ul>
                </div>
            </div>
            <!--end: User Bar -->
        </div>

        <!-- end:: Header Topbar -->
                </div>